### ISSUE TITLE
Bouncy Surfaces

### ISSUE THREAD

**Issue by Kihz17** [Curttree/INFO6024_GameComponentIntegration#18]
As a player I would like to be able to bounce off of certain surfaces so that I can be propelled to other areas. The propulsion force should be relative to my downwards velocity.

These surfaces will be strategically placed around the level so that they are imperative to solving certain puzzles. It should also be noted that these surfaces should also propel not only players, but objects as well.

**Comment by Curttree** [comment]
Marking as done as this seems to be working.
